### ISSUE TITLE
Add two more notebooks to the list?

### ISSUE THREAD

**Issue by htadashi** [tugstugi/dl-colab-notebooks#21]
Hello! I would like to suggest the addition of these two notebooks from works submitted to CPVR2020:

- Learning to See Through Obstructions: remove reflections, fences and water drops from photos
https://colab.research.google.com/drive/1iOKknc0dePekUH2TEh28EhcRPCS1mgwz

- 3D Photography using Context-aware Layered Depth Inpainting: create 3D photography from photos
https://colab.research.google.com/drive/1706ToQrkIZshRSJSHvZ1RuCiM__YX3Bz

Thanks for the list and have a happy Easter! :)

**Comment by tugstugi** [comment]
Hi htadashi, I have added the link to the "3D Photography using Context-aware Layered Depth Inpainting". I couldn't test the obstacle removing notebook because it needs a multiple frames from a single scene? I know there are some test images included in the notebook, but I wanted to test with extra independent data...

**Comment by htadashi** [comment]
Hi @tugstugi, thanks for the addition. Regarding the obstacle removing notebook, I think you are right. It must have a short sequence of images captured by a moving camera as an input. Maybe it would be better to edit this notebook to make it more user-friendly before adding it to your list.
